### ISSUE TITLE
'with_recording' に失敗した場合に、ログ出力でエラーが出る

### ISSUE THREAD

**Issue by sawadatsuyoshi-mf** [nalabjp/mysql_import#1]
@nalabjp 先日使ったときにこういう問題がありました。

https://github.com/nalabjp/mysql_import/blob/4c7212dc5c93ace1e1598a3787229d84b725d347/lib/mysql_import.rb#L70

で `yield` の実行に失敗して中断した場合、 `store[:exec_time]` は `nil` となる。その結果、

https://github.com/nalabjp/mysql_import/blob/4c7212dc5c93ace1e1598a3787229d84b725d347/lib/mysql_import.rb#L75

で `res` の2要素目に `nil` が記録され、

https://github.com/nalabjp/mysql_import/blob/4c7212dc5c93ace1e1598a3787229d84b725d347/lib/mysql_import.rb#L77

でそれが `@imported` にプッシュされる。そのために、ログ出力

https://github.com/nalabjp/mysql_import/blob/4c7212dc5c93ace1e1598a3787229d84b725d347/lib/mysql_import/logger.rb#L34

以降でエラーが出て、それ以上進まない。

直す必要あるかないか分かりませんが、報告しておきます。

**Comment by nalabjp** [comment]
@sawadatsuyoshi-mf 
Thank you for your report. 😀

It is specification to kill with runtime error.
However, it is not good to output an error at log output as a stack trace.
Would you show me output if possible?

**Comment by sawadatsuyoshi-mf** [comment]
Used with a failing fast seed file, it raises an error like this (actually, the error was caused on line 36 rather than 34, sorry):

```
.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/mysql_import-0.5.4/lib/mysql_import/logger.rb:36:in `format': can't convert nil into Float (TypeError)
from .rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/mysql_import-0.5.4/lib/mysql_import/logger.rb:36:in `block in import'
from .rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/mysql_import-0.5.4/lib/mysql_import/logger.rb:34:in `each'
from .rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/mysql_import-0.5.4/lib/mysql_import/logger.rb:34:in `import'
from ...
```

and it is due to `t[1]` being `nil`.

**Comment by nalabjp** [comment]
Thanks!

I will fix this to skip to output the import log if it raises a runtime error.
